### ISSUE TITLE
[REQUEST]: Add support for Apache

### ISSUE THREAD

**Issue by DRY411S** [SeattleDevs/letsencrypt-GoDaddy-hook#1]
hook.sh assumes that the cert will be deployed in nginx webserver. Could you add support for apache please?

**Comment by YasharF** [comment]
I would be happy to accept a PR.

**Comment by pyy** [comment]
@DRY411S 
This paragraph of code in  `hook.sh`  executes after successfully deploying SSL each time.
So you can change it to meet your requests.
   
```
deploy_cert() {
  cp "${KEYFILE}" "${FULLCHAINFILE}" /etc/nginx/ssl/; chown -R nginx: /etc/nginx/ssl
  systemctl reload nginx
}
```
:)
