### ISSUE TITLE
hooks/godaddy/hook.sh: line 39: KEYFILE: unbound variable

### ISSUE THREAD

**Issue by essare** [SeattleDevs/letsencrypt-GoDaddy-hook#3]
# $ ./dehydrated -c -d mydomain.com -t dns-01 -k 'hooks/godaddy/hook.sh'

 !! WARNING !! No main config file found, using default config!

 + Creating chain cache directory /home/ayoub/tmp/dehydrated/chains
Processing mydomain.com
 + Creating new directory /home/ayoub/tmp/dehydrated/certs/mydomain.com ...
 + Signing domains...
 + Generating private key...
 + Generating signing request...
 + Requesting new certificate order from CA...
 + Received 1 authorizations URLs from the CA
 + Handling authorization for mydomain.com
 + 1 pending challenge(s)
 + Deploying challenge tokens...
 - Setting TXT record with GoDaddy _acme-challenge.mydomain.com=ZK6-z8iI9en-PIbHl5Y4JwP0jDEwT7FyVRicjzUS1aF
 - Waiting 30 seconds for DNS to propagate.
 + Responding to challenge for mydomain.com authorization...
 + Challenge is valid!
 + Cleaning challenge tokens...
 - Removing TXT record from GoDaddy _acme-challenge.mydomain.com=--removed--
 + Requesting certificate...
 + Checking certificate...
 + Done!
 + Creating fullchain.pem...
hooks/godaddy/hook.sh: line 39: KEYFILE: unbound variable
ERROR: deploy_cert hook returned with non-zero exit code
# ayoub@workstation:~/tmp/dehydrated$

**Comment by YasharF** [comment]
Fixed by https://github.com/SeattleDevs/letsencrypt-GoDaddy-hook/pull/5
