### ISSUE TITLE
Please check your hook script, it should exit cleanly without doing anything on unknown/new hooks.

### ISSUE THREAD

**Issue by jeffsani** [SeattleDevs/letsencrypt-GoDaddy-hook#4]
Any idea why this may be failing?

# INFO: Using main config file /etc/dehydrated/config
./dehydrated: line 307: hook.sh: command not found
ERROR: Please check your hook script, it should exit cleanly without doing anything on unknown/new hooks.
./dehydrated: line 797: hook.sh: command not found
exit_hook returned with non-zero exit code!
root@letsencrypt:/etc/dehydrated#

**Comment by YasharF** [comment]
I think it is fixed by https://github.com/SeattleDevs/letsencrypt-GoDaddy-hook/pull/5 now
